apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: monitoring # Same namespace as deployment
  labels:
    app: kube-state-metrics
spec:
  selector:
    app: kube-state-metrics
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
    protocol: TCP
    nodePort: 32001 # Choose a NodePort in the range 30000-32767
  type: NodePort 