apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: database-dev
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mydb;
    USE mydb;

    CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'user';
    GRANT ALL PRIVILEGES ON mydb.* TO 'user'@'%';
    FLUSH PRIVILEGES;

    -- Criação da tabela de quartos
    CREATE TABLE IF NOT EXISTS rooms (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        capacity INT NOT NULL,
        available BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Criação da tabela de usuários
    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(255) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Criação da tabela de reservas
    CREATE TABLE IF NOT EXISTS reservations (
        id INT AUTO_INCREMENT PRIMARY KEY,
        room_id INT NOT NULL,
        user_name VARCHAR(100) NOT NULL,
        start_time DATETIME NOT NULL,
        end_time DATETIME NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (room_id) REFERENCES rooms(id),
        CONSTRAINT chk_time CHECK (start_time < end_time)
    );
