# Etapa 1: Build do Next.js
FROM node:18-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa 2: Imagem final standalone
FROM node:18-alpine
WORKDIR /app

# Copiar o app gerado no modo standalone
COPY --from=builder /app/.next/standalone/. ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Definir variáveis de ambiente
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Expor a porta do Next.js
EXPOSE 3000
EXPOSE 80

# Comando para iniciar o servidor
CMD ["node", "server.js"]
