# Etapa 1: Build do Next.js
FROM node:18-alpine AS builder
WORKDIR /app

# Recebe as variáveis no build
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_BACKEND_URL

# Definir as variáveis de ambiente dentro do container
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL

COPY package*.json ./
RUN npm install

COPY . .

# Faz o build com a variável embutida
RUN npm run build

# Etapa 2: Imagem final standalone
FROM node:18-alpine
WORKDIR /app

# Copiar o app gerado no modo standalone
COPY --from=builder /app/.next/standalone/ ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

EXPOSE 3000
EXPOSE 80

CMD ["node", "server.js"]