# Etapa 1: Construção
FROM node:18 AS builder
WORKDIR /app

# Copiar arquivos essenciais
COPY package.json package-lock.json ./
RUN npm install --frozen-lockfile

# Copiar código-fonte e construir a aplicação
COPY . .
RUN npm run build

# Etapa 2: Servidor de Produção
FROM node:18 AS runner
WORKDIR /app

# Copiar artefatos gerados na etapa anterior
COPY --from=builder /app/package.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

# Instalar apenas dependências de produção
RUN npm install --production --frozen-lockfile

# Definir variável de ambiente para execução em produção
ENV NODE_ENV=production

# Expor porta padrão do Next.js
EXPOSE 3000

# Comando para iniciar o servidor
CMD ["npm", "run", "start"]