version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_APP_URL: http://localhost:3000
        NEXT_PUBLIC_BACKEND_URL: http://localhost:8080
    ports:
      - "3000:3000"
