global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'gke-kubernetes'
    bearer_token: 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImRvemxtRW5yeFhkamU5X1hRTHNGQXEwVEpNMmV6Y2g4S0hMQnEtMUZKUUEifQ.eyJhdWQiOlsiaHR0cHM6Ly9jb250YWluZXIuZ29vZ2xlYXBpcy5jb20vdjEvcHJvamVjdHMvcHJvamV0by1pYWMtNDYyMTIzL2xvY2F0aW9ucy9zb3V0aGFtZXJpY2EtZWFzdDEtYS9jbHVzdGVycy9jbHVzdGVyLXByb2QiXSwiZXhwIjoxNzQ5NTE4MTQxLCJpYXQiOjE3NDk1MTQ1NDEsImlzcyI6Imh0dHBzOi8vY29udGFpbmVyLmdvb2dsZWFwaXMuY29tL3YxL3Byb2plY3RzL3Byb2pldG8taWFjLTQ2MjEyMy9sb2NhdGlvbnMvc291dGhhbWVyaWNhLWVhc3QxLWEvY2x1c3RlcnMvY2x1c3Rlci1wcm9kIiwianRpIjoiYzZlMzk4MDUtMDllYy00NTFiLTliNWQtNjJlZmRmY2Q1ODJkIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJtb25pdG9yaW5nIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InByb21ldGhldXMtZXh0ZXJuYWwiLCJ1aWQiOiJlNjA3ZmI1MC1kNWNlLTQzMzUtYWIxNC0xNDdkYjY1YzZmYmIifX0sIm5iZiI6MTc0OTUxNDU0MSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om1vbml0b3Jpbmc6cHJvbWV0aGV1cy1leHRlcm5hbCJ9.BJOi2bNLph2uOGTAhi2vD3SoUM87sn8xVmjah5MtOLoeYJbXiY6xr5-5iZpmpU5KPNBVc-o9HwzwUIFTgveii9uT23v6eFrd_OOHIg_Y41nDkPQVTrggzGAWGcZgqeQrTvurXsyVGHirSGtRote14rGjnOxXWyc5cWt3EY1jyqe4Ttbqi3ZLwQ0l0S809B5d2WbtxKrv4LJX04Yh1-4t5m-73Ui5X82sYlhTZbavA5v2K2xUpPlevf1Tng1nSvqZGt6PkSouLtjb2pO5_EgKUklC4EUjlIMdOiq-__laElhfzEucIPu0w3R1Gf1-_kmN_mKWo8G7NW6GyezZetbLBQ'
    kubernetes_sd_configs:
      - role: pod
        api_server: https://35.198.39.155
    tls_config:
      insecure_skip_verify: true

  #- job_name: 'backend'
  #  static_configs:
  #    - targets: ['34.95.147.47:8080']

  #- job_name: 'blackbox'
  #  metrics_path: /probe
  #  params:
  #    module: [http_2xx]
   # static_configs:
  #    - targets:
  #      - http://34.95.147.47:3000
  #  relabel_configs:
  #    - source_labels: [__address__]
    #    target_label: __param_target
  #    - source_labels: [__param_target]
  #      target_label: instance
  #    - target_label: __address__
  #      replacement: blackbox-exporter:9115 