global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'kubernetes-kube-state-metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['35.198.17.209:32001'] # IP do seu nó e a NodePort do kube-state-metrics

  - job_name: 'gke-kubernetes'
    kubernetes_sd_configs:
      - role: node
        api_server: https://35.198.39.155
        bearer_token: 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImRvemxtRW5yeFhkamU5X1hRTHNGQXEwVEpNMmV6Y2g4S0hMQnEtMUZKUUEifQ.eyJhdWQiOlsiaHR0cHM6Ly9jb250YWluZXIuZ29vZ2xlYXBpcy5jb20vdjEvcHJvamVjdHMvcHJvamV0by1pYWMtNDYyMTIzL2xvY2F0aW9ucy9zb3V0aGFtZXJpY2EtZWFzdDEtYS9jbHVzdGVycy9jbHVzdGVyLXByb2QiXSwiZXhwIjoxNzQ5Njg3NzE1LCJpYXQiOjE3NDk1MTQ5MTUsImlzcyI6Imh0dHBzOi8vY29udGFpbmVyLmdvb2dsZWFwaXMuY29tL3YxL3Byb2plY3RzL3Byb2pldG8taWFjLTQ2MjEyMy9sb2NhdGlvbnMvc291dGhhbWVyaWNhLWVhc3QxLWEvY2x1c3RlcnMvY2x1c3Rlci1wcm9kIiwianRpIjoiOWExNGU0OTctOWQ5Yy00MmQ0LTkxODQtNGU1YmVhYWYyNmQ3Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJtb25pdG9yaW5nIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InByb21ldGhldXMtZXh0ZXJuYWwiLCJ1aWQiOiJlNjA3ZmI1MC1kNWNlLTQzMzUtYWIxNC0xNDdkYjY1YzZmYmIifX0sIm5iZiI6MTc0OTUxNDkxNSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om1vbml0b3Jpbmc6cHJvbWV0aGV1cy1leHRlcm5hbCJ9.Majm4DPS69WvDG8C4pouMQfNzSmQTC8eC6hd2ujET_0T-9UMhBTKSK2F7LBXsvMgCDMKa58udiTAm3ityxpkHPY7EOb7m34WRva5jo2G6iMtO28oXNjn_ZOurIEXSUxfklZX95pjtiCweJPn16Uo6cl-ENVzU1cucfZkFd2SgtzcL1PuyolG4u0EOC_Zp9QFHUzzYnzBfc_Zh8gahuazt1rSb-VlT5ryw9GFlv-NbCG8PwOuZqu9PT6ourPHO19m3gAyL9Xjk4isDBzVXODAYEZprFXbIz2InI9DousdioskJV0GOAk1wBe_WHdgaRN68yvU1qXbsC3MPLB5a1PLMw'
        tls_config:
          insecure_skip_verify: true
      - role: pod
        api_server: https://35.198.39.155
        bearer_token: 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImRvemxtRW5yeFhkamU5X1hRTHNGQXEwVEpNMmV6Y2g4S0hMQnEtMUZKUUEifQ.eyJhdWQiOlsiaHR0cHM6Ly9jb250YWluZXIuZ29vZ2xlYXBpcy5jb20vdjEvcHJvamVjdHMvcHJvamV0by1pYWMtNDYyMTIzL2xvY2F0aW9ucy9zb3V0aGFtZXJpY2EtZWFzdDEtYS9jbHVzdGVycy9jbHVzdGVyLXByb2QiXSwiZXhwIjoxNzQ5Njg3NzE1LCJpYXQiOjE3NDk1MTQ5MTUsImlzcyI6Imh0dHBzOi8vY29udGFpbmVyLmdvb2dsZWFwaXMuY29tL3YxL3Byb2plY3RzL3Byb2pldG8taWFjLTQ2MjEyMy9sb2NhdGlvbnMvc291dGhhbWVyaWNhLWVhc3QxLWEvY2x1c3RlcnMvY2x1c3Rlci1wcm9kIiwianRpIjoiOWExNGU0OTctOWQ5Yy00MmQ0LTkxODQtNGU1YmVhYWYyNmQ3Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJtb25pdG9yaW5nIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InByb21ldGhldXMtZXh0ZXJuYWwiLCJ1aWQiOiJlNjA3ZmI1MC1kNWNlLTQzMzUtYWIxNC0xNDdkYjY1YzZmYmIifX0sIm5iZiI6MTc0OTUxNDkxNSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om1vbml0b3Jpbmc6cHJvbWV0aGV1cy1leHRlcm5hbCJ9.Majm4DPS69WvDG8C4pouMQfNzSmQTC8eC6hd2ujET_0T-9UMhBTKSK2F7LBXsvMgCDMKa58udiTAm3ityxpkHPY7EOb7m34WRva5jo2G6iMtO28oXNjn_ZOurIEXSUxfklZX95pjtiCweJPn16Uo6cl-ENVzU1cucfZkFd2SgtzcL1PuyolG4u0EOC_Zp9QFHUzzYnzBfc_Zh8gahuazt1rSb-VlT5ryw9GFlv-NbCG8PwOuZqu9PT6ourPHO19m3gAyL9Xjk4isDBzVXODAYEZprFXbIz2InI9DousdioskJV0GOAk1wBe_WHdgaRN68yvU1qXbsC3MPLB5a1PLMw'
        tls_config:
          insecure_skip_verify: true
      - role: service
        api_server: https://35.198.39.155
        bearer_token: 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImRvemxtRW5yeFhkamU5X1hRTHNGQXEwVEpNMmV6Y2g4S0hMQnEtMUZKUUEifQ.eyJhdWQiOlsiaHR0cHM6Ly9jb250YWluZXIuZ29vZ2xlYXBpcy5jb20vdjEvcHJvamVjdHMvcHJvamV0by1pYWMtNDYyMTIzL2xvY2F0aW9ucy9zb3V0aGFtZXJpY2EtZWFzdDEtYS9jbHVzdGVycy9jbHVzdGVyLXByb2QiXSwiZXhwIjoxNzQ5Njg3NzE1LCJpYXQiOjE3NDk1MTQ5MTUsImlzcyI6Imh0dHBzOi8vY29udGFpbmVyLmdvb2dsZWFwaXMuY29tL3YxL3Byb2plY3RzL3Byb2pldG8taWFjLTQ2MjEyMy9sb2NhdGlvbnMvc291dGhhbWVyaWNhLWVhc3QxLWEvY2x1c3RlcnMvY2x1c3Rlci1wcm9kIiwianRpIjoiOWExNGU0OTctOWQ5Yy00MmQ0LTkxODQtNGU1YmVhYWYyNmQ3Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJtb25pdG9yaW5nIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InByb21ldGhldXMtZXh0ZXJuYWwiLCJ1aWQiOiJlNjA3ZmI1MC1kNWNlLTQzMzUtYWIxNC0xNDdkYjY1YzZmYmIifX0sIm5iZiI6MTc0OTUxNDkxNSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om1vbml0b3Jpbmc6cHJvbWV0aGV1cy1leHRlcm5hbCJ9.Majm4DPS69WvDG8C4pouMQfNzSmQTC8eC6hd2ujET_0T-9UMhBTKSK2F7LBXsvMgCDMKa58udiTAm3ityxpkHPY7EOb7m34WRva5jo2G6iMtO28oXNjn_ZOurIEXSUxfklZX95pjtiCweJPn16Uo6cl-ENVzU1cucfZkFd2SgtzcL1PuyolG4u0EOC_Zp9QFHUzzYnzBfc_Zh8gahuazt1rSb-VlT5ryw9GFlv-NbCG8PwOuZqu9PT6ourPHO19m3gAyL9Xjk4isDBzVXODAYEZprFXbIz2InI9DousdioskJV0GOAk1wBe_WHdgaRN68yvU1qXbsC3MPLB5a1PLMw'
        tls_config:
          insecure_skip_verify: true

  #- job_name: 'backend'
  #  static_configs:
  #    - targets: ['34.95.147.47:8080']

  #- job_name: 'blackbox'
  #  metrics_path: /probe
  #  params:
  #    module: [http_2xx]
   # static_configs:
  #    - targets:
  #      - http://34.95.147.47:3000
  #  relabel_configs:
  #    - source_labels: [__address__]
    #    target_label: __param_target
  #    - source_labels: [__param_target]
  #      target_label: instance
  #    - target_label: __address__
  #      replacement: blackbox-exporter:9115 