- hosts: webserver
  become: yes
  tasks:
    - name: Configurar sudo sem senha para o usuário leona
      lineinfile:
        path: /etc/sudoers
        line: "leona ALL=(ALL) NOPASSWD: ALL"
        state: present
        validate: 'visudo -cf %s'

    - name: Update apt
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Add leona user to docker group
      user:
        name: leona
        groups: docker
        append: yes

    - name: Install iptables-persistent
      apt:
        name: iptables-persistent
        state: present

    - name: Create iptables directory
      file:
        path: /etc/iptables
        state: directory
        mode: '0755'

    - name: Configure iptables rules
      shell: |
        iptables -A FORWARD -i docker0 -o eth0 -j ACCEPT
        iptables -A FORWARD -i eth0 -o docker0 -j ACCEPT
        iptables -A FORWARD -i docker0 -o docker0 -j ACCEPT
        iptables-save > /etc/iptables/rules.v4
      args:
        creates: /etc/iptables/rules.v4

    - name: Clone o repositório
      git:
        repo: 'https://github.com/grupo9-uniamerica/mensal_04.git'
        dest: /home/leona/seuprojeto

    - name: Subir com docker-compose
      shell: docker-compose up -d
      args:
        chdir: /home/leona/seuprojeto
