- hosts: webserver
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Garantir que o diret칩rio sudoers.d existe
      file:
        path: /etc/sudoers.d
        state: directory
        mode: '0755'

    - name: Configurar sudo sem senha para o usu치rio leona
      copy:
        content: "leona ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/leona
        mode: '0440'
        validate: 'visudo -cf %s'
      become: yes
      become_method: sudo

    - name: Garantir que o usu치rio leona existe
      user:
        name: leona
        state: present
        groups: sudo
        append: yes
      become: yes
      become_method: sudo

    - name: Update apt
      apt:
        update_cache: yes
        upgrade: dist
      become: yes
      become_method: sudo

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: yes
      become_method: sudo

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
      become: yes
      become_method: sudo

    - name: Add leona user to docker group
      user:
        name: leona
        groups: docker
        append: yes
      become: yes
      become_method: sudo

    - name: Install iptables-persistent
      apt:
        name: iptables-persistent
        state: present
      become: yes
      become_method: sudo

    - name: Create iptables directory
      file:
        path: /etc/iptables
        state: directory
        mode: '0755'
      become: yes
      become_method: sudo

    - name: Configure iptables rules
      shell: |
        iptables -A FORWARD -i docker0 -o eth0 -j ACCEPT
        iptables -A FORWARD -i eth0 -o docker0 -j ACCEPT
        iptables -A FORWARD -i docker0 -o docker0 -j ACCEPT
        iptables-save > /etc/iptables/rules.v4
      args:
        creates: /etc/iptables/rules.v4
      become: yes
      become_method: sudo

    - name: Clone o reposit칩rio
      git:
        repo: 'https://github.com/grupo9-uniamerica/mensal_04.git'
        dest: /home/leona/seuprojeto
      become: yes
      become_method: sudo

    - name: Subir com docker-compose
      shell: docker-compose up -d
      args:
        chdir: /home/leona/seuprojeto
      become: yes
      become_method: sudo
