- hosts: webserver
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install iptables-persistent
      apt:
        name: iptables-persistent
        state: present

    - name: Create iptables directory
      file:
        path: /etc/iptables
        state: directory
        mode: '0755'

    - name: Configure iptables rules
      shell: |
        iptables -A FORWARD -i docker0 -o eth0 -j ACCEPT
        iptables -A FORWARD -i eth0 -o docker0 -j ACCEPT
        iptables -A FORWARD -i docker0 -o docker0 -j ACCEPT
        iptables-save > /etc/iptables/rules.v4
      args:
        creates: /etc/iptables/rules.v4

    - name: Remover diretório do projeto se existir
      file:
        path: /home/ubuntu/seuprojeto
        state: absent

    - name: Clone o repositório
      git:
        repo: 'https://github.com/grupo9-uniamerica/mensal_04.git'
        dest: /home/ubuntu/seuprojeto
        version: master
        force: yes

    - name: Subir com docker-compose
      shell: |
        cd /home/ubuntu/seuprojeto
        docker-compose down
        docker-compose up -d --build
