apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
data:
  NODE_ENV: "production"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_PUBLIC_BASE_URL: "http://35.198.60.97"
  NEXT_PUBLIC_APP_URL: "http://35.198.60.97"
