name: Deploy to Development

on:
  push:
    branches: [ stage ]

env:
  GKE_CLUSTER: cluster-prod
  GKE_ZONE: southamerica-east1-a
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_STAGING }}

  DOCKER_USER: loungegario
  FRONT_IMAGE: loungegario/frontend-dev:latest
  BACK_IMAGE: loungegario/backend-dev:latest

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      k8s: ${{ steps.filter.outputs.k8s }}
    steps:
      - uses: actions/checkout@v3

      - name: Check file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
            k8s:
              - 'k8s/dev/**'

  build-and-deploy:
    needs: changes
    runs-on: ubuntu-latest
    if: needs.changes.outputs.frontend == 'true' || needs.changes.outputs.backend == 'true' || needs.changes.outputs.k8s == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and Push Frontend
        if: needs.changes.outputs.frontend == 'true'
        run: |
          docker build \
            --no-cache \
            --build-arg NEXT_PUBLIC_APP_URL=http://34.151.227.32 \
            --build-arg NEXT_PUBLIC_BACKEND_URL=http://backend.backend-dev.svc.cluster.local:8080 \
            -t $FRONT_IMAGE ./frontend
          docker push $FRONT_IMAGE

      - name: Build and Push Backend
        if: needs.changes.outputs.backend == 'true'
        run: |
          docker build -t $BACK_IMAGE ./backend
          docker push $BACK_IMAGE

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_STAGING }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Install GKE gcloud auth plugin
        run: gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

      # ------------------------
      # NOVO BLOCO - Namespaces
      # ------------------------
      - name: Ensure Kubernetes Namespaces Exist
        run: |
          kubectl create namespace frontend-dev --dry-run=client -o yaml | kubectl apply -f -
          kubectl create namespace backend-dev --dry-run=client -o yaml | kubectl apply -f -
          kubectl create namespace database-dev --dry-run=client -o yaml | kubectl apply -f -

      # ------------------------
      # Aplicar os manifests
      # ------------------------
      - name: Apply Kubernetes Manifests
        if: needs.changes.outputs.k8s == 'true'
        run: |
          kubectl apply -f k8s/dev/

      # ------------------------
      # Atualizar imagens se houve alteração
      # ------------------------
      - name: Update frontend deployment
        if: needs.changes.outputs.frontend == 'true'
        run: |
          kubectl set image deployment/frontend frontend=$FRONT_IMAGE -n frontend-dev

      - name: Update backend deployment
        if: needs.changes.outputs.backend == 'true'
        run: |
          kubectl set image deployment/backend backend=$BACK_IMAGE -n backend-dev

      # ------------------------
      # Reiniciar os deployments e aguardar
      # ------------------------
      - name: Restart and Wait for Deployments
        run: |
          if [ "${{ needs.changes.outputs.frontend }}" == "true" ]; then
            # Remove todos os pods antigos do frontend
            kubectl delete pod -l app=frontend -n frontend-dev --grace-period=0 --force || true
            while kubectl get pods -n frontend-dev -l app=frontend | grep -q frontend; do sleep 2; done

            kubectl rollout restart deployment/frontend -n frontend-dev
            kubectl rollout status deployment/frontend -n frontend-dev --timeout=300s
          fi

          if [ "${{ needs.changes.outputs.backend }}" == "true" ]; then
            kubectl rollout restart deployment/backend -n backend-dev
            kubectl rollout status deployment/backend -n backend-dev --timeout=300s
          fi
